# Generated by Django 2.0 on 2020-01-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DXYData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics', models.TextField(blank=True, verbose_name='顶部数据')),
                ('rumor', models.TextField(blank=True, verbose_name='辟谣数据')),
                ('timeline', models.TextField(blank=True, verbose_name='时间线新闻数据')),
                ('domestic_province', models.TextField(blank=True, verbose_name='国内省级数据')),
                ('domestic_area', models.TextField(blank=True, verbose_name='国内地区数据')),
                ('foreign', models.TextField(blank=True, verbose_name='国外数据')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(verbose_name='修改时间')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('remark', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name': '丁香园数据',
                'verbose_name_plural': '丁香园数据',
                'db_table': 'wuhan2020_DXY_Data',
                'ordering': ['-id'],
                'managed': True,
            },
        ),
    ]
