# Generated by Django 2.0 on 2020-02-09 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
        ('wuhan2020', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DXYTimeLine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('source_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='来源链接')),
                ('source_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='来源名称')),
                ('source_summary', models.TextField(blank=True, null=True, verbose_name='来源详情')),
                ('info_type', models.IntegerField(blank=True, null=True, verbose_name='消息类型')),
                ('publish_time', models.DateTimeField(verbose_name='发布时间')),
                ('create_time', models.DateTimeField(verbose_name='采集时间')),
                ('modify_time', models.DateTimeField(verbose_name='最后修改时间')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.AdministrativeDiv', verbose_name='省份')),
            ],
            options={
                'verbose_name': '丁香园发展时间线',
                'verbose_name_plural': '丁香园发展时间线',
                'db_table': 'wuhan2020_DXY_timeline',
                'ordering': ['-id'],
                'managed': True,
            },
        ),
    ]
